version: 'version'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Corne01214!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
